CONFIG_I2C=y
CONFIG_ADC=y
CONFIG_ADC_NRFX_SAADC=y
CONFIG_LOG=y
CONFIG_PWM=y
CONFIG_BT=y
CONFIG_WATCHDOG=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_MAX_CONN=1
CONFIG_BT_DEVICE_NAME="Drone_FC"
CONFIG_MPU6050=n
CONFIG_SYS_CLOCK_TICKS_PER_SEC=32768


CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_CBPRINTF_FP_SUPPORT=y

# Enable detailed hardware crash dumping
CONFIG_DEBUG=y
CONFIG_FAULT_DUMP=2
